MODULE PCRTM_RT_SOLUTION_DEFINE

  USE PCRTM_TYPE_KIND
  USE PCRTM_ATM_ABSORPTION_DEFINE, ONLY : PCRTM_ATM_ABS_STRUCT_TYPE

  TYPE PCRTM_RT_SOLUTION_TYPE
     REAL(SINGLE), ALLOCATABLE :: RADUP(:)
     REAL(SINGLE), ALLOCATABLE :: RADDN(:)
     REAL(SINGLE), ALLOCATABLE :: RADDNCLD(:)
     REAL(SINGLE), ALLOCATABLE :: BS(:)
     REAL(SINGLE), ALLOCATABLE :: BLAY(:,:) 
     REAL(SINGLE), ALLOCATABLE :: EMIS(:)
     REAL(SINGLE), ALLOCATABLE :: TRTOP2LV(:,:)
     REAL(SINGLE), ALLOCATABLE :: TRLAY(:,:)
     REAL(SINGLE), ALLOCATABLE :: DBDT(:,:)
     REAL(SINGLE), ALLOCATABLE :: DBSDTS(:)
     REAL(SINGLE), ALLOCATABLE :: TAULAY(:,:)
     REAL(SINGLE), ALLOCATABLE :: TAUGAS_ABOVE(:)
     REAL(SINGLE), ALLOCATABLE :: TAUGAS_BELOW(:)
  END TYPE PCRTM_RT_SOLUTION_TYPE
  
CONTAINS
  
  SUBROUTINE INIT_PCRTM_RT_SOLUTION( RT_SOLUTION, PCRTM_STND )
    TYPE(PCRTM_RT_SOLUTION_TYPE), INTENT(OUT)    :: RT_SOLUTION
    TYPE(PCRTM_ATM_ABS_STRUCT_TYPE),INTENT(IN)   :: PCRTM_STND

    INTEGER :: ALLOC_STAT
    INTEGER :: NM
    INTEGER :: NLAY, NLEV


    NM     = PCRTM_STND%NM
    NLAY   = PCRTM_STND%NLAY
    NLEV   = PCRTM_STND%NLEV

    ALLOCATE(RT_SOLUTION%RADUP(NM),          &
             RT_SOLUTION%RADDN(NM),          &
             RT_SOLUTION%RADDNCLD(NM),       &
             RT_SOLUTION%BS(NM),             &
             RT_SOLUTION%BLAY(NM,NLAY),      &
             RT_SOLUTION%EMIS(NM),           &
             RT_SOLUTION%TRTOP2LV(NM,NLEV),  &
             RT_SOLUTION%TRLAY(NM,NLAY),     &
             RT_SOLUTION%DBDT(NM,NLAY),      &
             RT_SOLUTION%DBSDTS(NM),         &
             RT_SOLUTION%TAULAY(NM,NLAY),    &
             RT_SOLUTION%TAUGAS_ABOVE(NM),   &
             RT_SOLUTION%TAUGAS_BELOW(NM),   &
             STAT = ALLOC_STAT)
             
    IF ( ALLOC_STAT /= 0 ) THEN
       PRINT*,'ERROR TRYING TO ALLOCATE RT_SOLUTION'
       STOP
    ENDIF

    RT_SOLUTION%RADDNCLD= 0.0
    RT_SOLUTION%RADDN   = 0.0
    RT_SOLUTION%RADUP   = 0.0
    RT_SOLUTION%BS      = 0.0
    RT_SOLUTION%BLAY    = 0.0
    RT_SOLUTION%EMIS    = 0.0
    RT_SOLUTION%TRTOP2LV= 1
    RT_SOLUTION%TRLAY   = 1
    RT_SOLUTION%DBDT    = 0.0
    RT_SOLUTION%DBSDTS  = 0.0
    RT_SOLUTION%TAULAY  = 0
    RT_SOLUTION%TAUGAS_ABOVE=0
    RT_SOLUTION%TAUGAS_BELOW=0

  END SUBROUTINE INIT_PCRTM_RT_SOLUTION


  SUBROUTINE CLEAR_PCRTM_RT_SOLUTION( RT_SOLUTION )
    TYPE(PCRTM_RT_SOLUTION_TYPE), INTENT(INOUT)  :: RT_SOLUTION
    INTEGER :: DEALLOC_STAT
    
    DEALLOCATE(RT_SOLUTION%RADUP,      &
               RT_SOLUTION%RADDN,      &
               RT_SOLUTION%RADDNCLD,   &
               RT_SOLUTION%BS,         &
               RT_SOLUTION%BLAY,       &
               RT_SOLUTION%EMIS,       &
               RT_SOLUTION%TRTOP2LV,   &
               RT_SOLUTION%TRLAY,      &
               RT_SOLUTION%DBDT,       &
               RT_SOLUTION%DBSDTS,     &
               RT_SOLUTION%TAULAY,     &
               RT_SOLUTION%TAUGAS_ABOVE,&
               RT_SOLUTION%TAUGAS_BELOW,&
               STAT = DEALLOC_STAT)
             
    IF ( DEALLOC_STAT /= 0 ) THEN
       PRINT*,'ERROR TRYING TO DEALLOCATE RT_SOLUTION'
       STOP
    ENDIF

  END SUBROUTINE CLEAR_PCRTM_RT_SOLUTION

END MODULE PCRTM_RT_SOLUTION_DEFINE
