MODULE PCRTM_ATM_ABSORPTION_DEFINE
  USE PCRTM_TYPE_KIND

  TYPE PCRTM_ATM_ABSORPTION_TYPE
     !ABSORPTION COEFFICIENTS
     REAL(SINGLE),ALLOCATABLE :: KGAS(:,:,:,:)
     REAL(SINGLE),ALLOCATABLE :: KH2O2(:,:,:),KH2O3(:,:,:),KH2O1(:,:,:)
  END TYPE PCRTM_ATM_ABSORPTION_TYPE

  TYPE PCRTM_ATM_ABS_STRUCT_TYPE
     INTEGER     :: NT        ! NUMBER OF STANDARD TEMPERATURE PROFILE
     INTEGER     :: NLAY      ! NUMBER OF ATMOPHERE LAYER
     INTEGER     :: NMOL      ! NUMBER OF ABSORBER MOLECULE SPECIES
     INTEGER     :: NLEV      ! NUMBER OF ATMOPHERE LEVEL
     INTEGER     :: NM        ! NUMBER OF ABSOPRTION LINES IN MONO FREQ DOMAIN
     INTEGER,ALLOCATABLE       :: MOLINDX(:)
     REAL(SINGLE),ALLOCATABLE       :: SCALFAC(:)
     REAL(SINGLE),ALLOCATABLE  :: GASSTD(:,:,:) !(NLAY,NT,NG)
     !STANDARD US T, AND GAS PROFILES. STDPROF IS THE SCALED PROFILE.
     REAL(SINGLE),ALLOCATABLE  :: TSTD(:,:)     !(NLAY,NT)
     REAL(SINGLE),ALLOCATABLE  :: FIXAMT(:,:)   !(NT,NLAY)
     REAL(SINGLE),ALLOCATABLE  :: PBND(:)       !NLEV
     REAL(DOUBLE),ALLOCATABLE  :: FRQ(:)        !NM
     INTEGER,ALLOCATABLE       :: NGAS(:),IDGAS(:,:)
  END TYPE PCRTM_ATM_ABS_STRUCT_TYPE

CONTAINS
  
  SUBROUTINE INIT_PCRTM_ATM_ABS_STRUCT( PCRTM_STND,&
                                        NLAY,      &
                                        NT,        &
                                        NMOL,      &
                                        NM )
    TYPE(PCRTM_ATM_ABS_STRUCT_TYPE), &
                            INTENT(OUT) :: PCRTM_STND
    INTEGER, INTENT (IN) :: NLAY, NT, NMOL, NM
    INTEGER :: ALLOC_STAT
    
    PCRTM_STND%NLAY = NLAY
    PCRTM_STND%NLEV = NLAY + 1
    PCRTM_STND%NT   = NT
    PCRTM_STND%NMOL = NMOL
    PCRTM_STND%NM   = NM


    ALLOCATE(PCRTM_STND%MOLINDX(NMOL),              &
             PCRTM_STND%SCALFAC(NMOL),              &
             PCRTM_STND%GASSTD(NLAY,NT,NMOL),       &
             PCRTM_STND%TSTD(NLAY,NT),              &
             PCRTM_STND%FIXAMT(NT,NLAY),            &
             PCRTM_STND%PBND(NLAY+1),               &
             PCRTM_STND%FRQ(NM),                    &
             PCRTM_STND%NGAS(NM),                   &
             PCRTM_STND%IDGAS(NMOL+1,NM),           &
             STAT = ALLOC_STAT )
    
    IF ( ALLOC_STAT /= 0 ) THEN
       PRINT*,'ERROR TRYING TO ALLOCATE PCRTM_STND'
       STOP
    ENDIF
    
    PCRTM_STND%MOLINDX = 2  !DEFAULT VALUE  2-ABSORBER INCLUDED, 1-ABSORBER NOT INCLUDED
    PCRTM_STND%SCALFAC = 1
    PCRTM_STND%GASSTD  = 0
    PCRTM_STND%TSTD    = 0
    PCRTM_STND%FIXAMT  = 0
    PCRTM_STND%PBND    = 0 
    PCRTM_STND%FRQ     = 0
    PCRTM_STND%NGAS    = 0
    PCRTM_STND%IDGAS   = 0

  END SUBROUTINE INIT_PCRTM_ATM_ABS_STRUCT

  SUBROUTINE CLEAR_PCRTM_ATM_ABS_STRUCT( PCRTM_STND )  
    TYPE(PCRTM_ATM_ABS_STRUCT_TYPE), INTENT(INOUT) :: PCRTM_STND
    INTEGER :: DEALLOC_STAT
    
    DEALLOCATE(PCRTM_STND%MOLINDX,              &
               PCRTM_STND%SCALFAC,              &
               PCRTM_STND%GASSTD,               &
               PCRTM_STND%TSTD,                 &
               PCRTM_STND%FIXAMT,               &
               PCRTM_STND%PBND,                 &
               PCRTM_STND%FRQ,                  &
               PCRTM_STND%NGAS,                 &
               PCRTM_STND%IDGAS,                &
               STAT = DEALLOC_STAT )
    
    IF ( DEALLOC_STAT /= 0 ) THEN
       PRINT*,'ERROR TRYING TO DEALLOCATE PCRTM_STND'
       STOP
    ENDIF

  END SUBROUTINE CLEAR_PCRTM_ATM_ABS_STRUCT


  SUBROUTINE INIT_PCRTM_ATM_ABSORPTION(PCRTM_ATM_ABSORPTION_PARAM, PCRTM_STND)
    TYPE(PCRTM_ATM_ABSORPTION_TYPE),INTENT(OUT) :: PCRTM_ATM_ABSORPTION_PARAM
    TYPE(PCRTM_ATM_ABS_STRUCT_TYPE),INTENT(IN)  :: PCRTM_STND

    INTEGER :: ALLOC_STAT
    INTEGER :: NLAY, NT, NMOL, NM


    NLAY   = PCRTM_STND%NLAY
    NT     = PCRTM_STND%NT
    NMOL   = PCRTM_STND%NMOL
    NM     = PCRTM_STND%NM
    ALLOCATE(PCRTM_ATM_ABSORPTION_PARAM%KGAS(NMOL,NM,NLAY,NT),      &
             PCRTM_ATM_ABSORPTION_PARAM%KH2O1(NM,NLAY,NT),          &
             PCRTM_ATM_ABSORPTION_PARAM%KH2O2(NM,NLAY,NT),          &
             PCRTM_ATM_ABSORPTION_PARAM%KH2O3(NM,NLAY,NT),          &
             STAT = ALLOC_STAT )
    
    IF ( ALLOC_STAT /= 0 ) THEN
       PRINT*,'ERROR TRYING TO ALLOCATE PCRTM_ATM_ABSORPTION_PARAM'
       STOP
    ENDIF

    PCRTM_ATM_ABSORPTION_PARAM%KGAS      =  0
    PCRTM_ATM_ABSORPTION_PARAM%KH2O1     =  0
    PCRTM_ATM_ABSORPTION_PARAM%KH2O2     =  0
    PCRTM_ATM_ABSORPTION_PARAM%KH2O3     =  0
    
  END SUBROUTINE INIT_PCRTM_ATM_ABSORPTION
  
  SUBROUTINE CLEAR_PCRTM_ATM_ABSORPTION(PCRTM_ATM_ABSORPTION_PARAM)
    TYPE(PCRTM_ATM_ABSORPTION_TYPE),INTENT(INOUT)    :: PCRTM_ATM_ABSORPTION_PARAM

    INTEGER :: DEALLOC_STAT
    
    DEALLOCATE(PCRTM_ATM_ABSORPTION_PARAM%KGAS,       &
               PCRTM_ATM_ABSORPTION_PARAM%KH2O1,      &
               PCRTM_ATM_ABSORPTION_PARAM%KH2O2,      &
               PCRTM_ATM_ABSORPTION_PARAM%KH2O3,      &
               STAT = DEALLOC_STAT )   
    
    IF ( DEALLOC_STAT /= 0 ) THEN
       PRINT*,'ERROR TRYING TO DEALLOCATE PCRTM_ATM_ABSORPTION_PARAM'
       STOP
    ENDIF
    
  END SUBROUTINE CLEAR_PCRTM_ATM_ABSORPTION
  
END MODULE PCRTM_ATM_ABSORPTION_DEFINE

